[pipelex.log_config]
default_log_level = "INFO"

[pipelex.log_config.package_log_levels]
pipelex = "INFO"

[cogt.llm_config]
# is_dump_text_prompts_enabled = true
# is_dump_response_text_enabled = true

[cogt.llm_config.instructor_config]
# is_dump_kwargs_enabled = true
# is_dump_response_enabled = true
# is_dump_error_enabled = true

[pipelex.observer_config]
observer_dir = "results/observer"

[pipelex.feature_config]
# WIP/Experimental feature flags
# is_pipeline_tracking_enabled = true
# is_activity_tracking_enabled = true
is_reporting_enabled = true
